find_package(VexCL)
if(VexCL_FOUND)
  get_property(VEXCL_INCLUDE_DIRS TARGET VexCL::Common PROPERTY INTERFACE_INCLUDE_DIRECTORIES)
  get_property(VEXCL_LINK_LIBRARIES TARGET VexCL::Common PROPERTY INTERFACE_LINK_LIBRARIES)
  get_property(VEXCL_COMPILE_DEFINITIONS TARGET VexCL::OpenCL PROPERTY INTERFACE_COMPILE_DEFINITIONS)
  set(VEXCL_LINK_LIBRARIES "${VEXCL_LINK_LIBRARIES};OpenCL::OpenCL")
  add_library(OPM::VexCL::OpenCL INTERFACE IMPORTED)
  set_target_properties(OPM::VexCL::OpenCL PROPERTIES
    INTERFACE_COMPILE_DEFINITIONS "${VEXCL_COMPILE_DEFINITIONS}"
    INTERFACE_LINK_LIBRARIES "${VEXCL_LINK_LIBRARIES}")
  target_include_directories(OPM::VexCL::OpenCL SYSTEM INTERFACE "${VEXCL_INCLUDE_DIRS}")
else()
  add_library(OPM::VexCL::OpenCL INTERFACE IMPORTED)
endif()